### ISSUE TITLE
Death Maps are broken

### ISSUE THREAD

**Issue by Folas1337** [mfnalex/AngelChest#36]
If I enable "death-maps" in the config, I start receiving the following error whenever I die with something in my inventory/spawn an AngelChest: <https://pastes.dev/DpZRwcllJM>

**Comment by Tizooo** [comment]
same here

**Comment by mfnalex** [comment]
Thanks for reporting, and sorry for the late reply. Will be fixed within 24 hours. Until then please disable death maps.

**Comment by mfnalex** [comment]
Fixed in JeffLib 14.2.1 https://github.com/mfnalex/JeffLib/commit/66b0ed894f78685cddfe194592c37d6890b68550 / AngelChest 13.2.0
